### ISSUE TITLE
Stuck at wallpaper

### ISSUE THREAD

**Issue by celka** [koansoftware/koan-stm32mp-bsp-repo#1]
Hello
I successfully built an image(from this article:  https://koansoftware.com/yocto-project-meta-layer-for-stm32mp1-by-koan/#top , openstlinux-eglfs,st-example-image-qt)(with ubuntu 14) to STM32MP157C-EV1 board, put it on sdcard with dd.
It boots, but I have only a wallpaper, no mouse, with ctrl+alt+del it reboots.
I cant even open a terminal,it even doenst assign an ip if I attach an UTP cable so I cannot login to it via ssh,  so I cannot really use 
it.
![kép](https://user-images.githubusercontent.com/1615587/91154362-bbad6100-e6c1-11ea-9b81-3873040f119e.png)

Am I missing something?
thanks

**Comment by koansoftware** [comment]
@celka please login using the serial debug port.

**Comment by celka** [comment]
> 
> 
> @celka please login using the serial debug port.

Hello
thanks, can u help me how to login with the serial debug port?

**Comment by koansoftware** [comment]
**System Login**
Poky linux login is the standard one:
-  Username : root
-  Password : <no password, press enter>
