### ISSUE TITLE
QT5 QuickControls 2

### ISSUE THREAD

**Issue by RBEGamer** [koansoftware/koan-stm32mp-bsp-repo#2]
Hello,
The build process was easy. After flashing the image, i noticed that the QT5 QuickControls and QuickControls 2 Libraries are missing in the image. So i was unable to build a QT Quick application for the STM32MP1 Board.
Is there a solution to get QT QuickControls build for the image using yocto ?

**Comment by koansoftware** [comment]
Hi @RBEGamer,
as I stated in my [presentation here](https://koansoftware.com/koan-at-qtday-2019/)

You should add
```
IMAGE_INSTALL_append = " qtquickcontrols \
qtquickcontrols­qmlplugins \
qtquickcontrols2 \
qtquickcontrols2­qmlplugins”
```
--
Marco
